# This is a basic workflow to help you get started with Actions

name: Go Formatter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: uno@master
      with:
        fetch-depth: 0
    - name: Golang Formatter
      uses: sladyn98/auto-go-format@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
